# Generated by Django 5.0.2 on 2024-02-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_machine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='machine_name',
        ),
    ]
