# Generated by Django 5.0.2 on 2024-02-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['name'], 'verbose_name': 'Страницы', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя страницы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
