# Generated by Django 5.0.2 on 2024-03-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options_alter_page_image_alter_page_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='text',
        ),
        migrations.AddField(
            model_name='page',
            name='text_1',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 1'),
        ),
        migrations.AddField(
            model_name='page',
            name='text_2',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 2'),
        ),
        migrations.AddField(
            model_name='page',
            name='text_3',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 3'),
        ),
    ]
