# Generated by Django 5.0.2 on 2024-04-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_page_text_page_text_1_page_text_2_page_text_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя страницы')),
                ('machine_name', models.CharField(max_length=255, unique=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото1')),
                ('text_1', models.TextField(blank=True, null=True, verbose_name='Текст 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото2')),
                ('text_2', models.TextField(blank=True, null=True, verbose_name='Текст 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото3')),
                ('text_3', models.TextField(blank=True, null=True, verbose_name='Текст 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото4')),
                ('text_4', models.TextField(blank=True, null=True, verbose_name='Текст 4')),
            ],
            options={
                'verbose_name': 'Страница Спецэффектов',
                'verbose_name_plural': 'Страница Спецэффектов',
            },
        ),
    ]
