# Generated by Django 5.0.2 on 2024-06-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_pagespecial_image_5_pagespecial_name_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagespecial',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 6'),
        ),
        migrations.AddField(
            model_name='pagespecial',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 7'),
        ),
        migrations.AddField(
            model_name='pagespecial',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 8'),
        ),
        migrations.AddField(
            model_name='pagespecial',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 9'),
        ),
        migrations.AddField(
            model_name='pagespecial',
            name='name_6',
            field=models.CharField(max_length=255, null=True, verbose_name='Название спецэффекта 6'),
        ),
        migrations.AddField(
            model_name='pagespecial',
            name='name_7',
            field=models.CharField(max_length=255, null=True, verbose_name='Название спецэффекта 7'),
        ),
        migrations.AddField(
            model_name='pagespecial',
            name='name_8',
            field=models.CharField(max_length=255, null=True, verbose_name='Название спецэффекта 8'),
        ),
        migrations.AddField(
            model_name='pagespecial',
            name='name_9',
            field=models.CharField(max_length=255, null=True, verbose_name='Название спецэффекта 9'),
        ),
        migrations.AddField(
            model_name='pagespecial',
            name='text_6',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 6'),
        ),
        migrations.AddField(
            model_name='pagespecial',
            name='text_7',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 7'),
        ),
        migrations.AddField(
            model_name='pagespecial',
            name='text_8',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 8'),
        ),
        migrations.AddField(
            model_name='pagespecial',
            name='text_9',
            field=models.TextField(blank=True, null=True, verbose_name='Текст 9'),
        ),
        migrations.AlterField(
            model_name='pagespecial',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='pagespecial',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='pagespecial',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='pagespecial',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='pagespecial',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='pagespecial',
            name='name_1',
            field=models.CharField(max_length=255, null=True, verbose_name='Название спецэффекта 1'),
        ),
        migrations.AlterField(
            model_name='pagespecial',
            name='name_2',
            field=models.CharField(max_length=255, null=True, verbose_name='Название спецэффекта 2'),
        ),
        migrations.AlterField(
            model_name='pagespecial',
            name='name_3',
            field=models.CharField(max_length=255, null=True, verbose_name='Название спецэффекта 3'),
        ),
        migrations.AlterField(
            model_name='pagespecial',
            name='name_4',
            field=models.CharField(max_length=255, null=True, verbose_name='Название спецэффекта 4'),
        ),
        migrations.AlterField(
            model_name='pagespecial',
            name='name_5',
            field=models.CharField(max_length=255, null=True, verbose_name='Название спецэффекта 5'),
        ),
    ]
